### PR TITLE
feat: Add local DB setup from DB layer

### PR DESCRIPTION
**Pull request by kulla**
First step: Add local setup for DB from database layer. `yarn migrate:ts` works fine after `yarn start`:

```
Ignoring invalid configuration option passed to Connection: driver. This is currently a warning, but in future versions of MySQL2, an error will be thrown if you pass an invalid configuration option to a Connection
[INFO] Processed migration 20220517163100-add-image-caption
[INFO] Processed migration 20220614111600-make-subjects-in-construction-a-subject
[INFO] Processed migration 20220625191600-delete-trashed-static-pages
[INFO] Processed migration 20220625202000-convert-important-and-blockquote-to-box
[INFO] Processed migration 20230526090000-remove-empty-tables
[INFO] Processed migration 20230526090001-convert-table-to-serlo-table
[INFO] Done
```

### CODE REVIEW

**Comment by AndreasHuber** [comment]
Have you seen https://github.com/serlo/local-dev-env/issues/14  or the comments in https://github.com/serlo/database-layer/issues/456?

**Comment by kulla** [comment]
> Have you seen [serlo/local-dev-env#14](https://github.com/serlo/local-dev-env/issues/14) or the comments in [serlo/database-layer#456](https://github.com/serlo/database-layer/issues/456)?

For me those are follow ups. Currently we need a first setup to better test DB migrations (locally + via GitHub workflows). Those issues can be implemented in the future. With https://github.com/serlo/configure-repositories those improvements can be easily migrated to other repos afterwards as well...

**Comment by AndreasHuber** [comment]
The reason why I would have liked to avoid having a whole database in the git history is that it significantly increases size and therefore cloning time of the repository, even if at a later point it is removed.

**Comment by kulla** [comment]
> The reason why I would have liked to avoid having a whole database in the git history is that it significantly increases size and therefore cloning time of the repository, even if at a later point it is removed.

I know, however we already have added https://github.com/serlo/db-migrations/tree/main/.yarn/cache to the repo which is much bigger than the `sql` file.

When you think about: Even when we store the sql file somewhere else (for example in a separate docker container) the content need to be downloaded and need to be stored at the disc. So it doesn't make a difference whether you download it via `git clone` or later when you call `docker compose up`. The downside is of course that with `git clone` each version of the `sql` file is downloaded (can be prevented with partial clones). The advantage though is that after a `git clone` you nether need to download the sql file again even when you switch between different version. See https://yarnpkg.com/features/zero-installs#what-does-this-do-to-my-repository-size for more info.

So far the theory whether we want it, is another question though...

**Review by hugotiburtino — DISMISSED** [review]

**Comment by eliflores** [comment]
> We would like to give a try to moving the MySQL database pieces into a separate repository where we build a Docker image that can be re-used by different Serlo repositories ✨

Done in [3b0a95a](https://github.com/serlo/db-migrations/pull/75/commits/3b0a95a9c736d8dc7d0e1be90ee9b99ab1dad851) ✨

**Review by eliflores — APPROVED** [review]

**Pull request merged**
